// Generated by build.py. Edit the template there, not this file.
//
// Cache-first with a background refresh: an installed copy opens instantly and
// works with no signal, and each visit quietly re-fetches what it served. A new
// build changes VERSION, so the install step below replaces the whole cache.

const VERSION = 'f6e4d6d0986bb37b';
const CACHE = 'recipes-' + VERSION;
const SCOPE = '/recipes/';
const START_URL = '/recipes/';
const PRECACHE = [
  "/recipes/assets/favicon.svg",
  "/recipes/assets/icon-192.png",
  "/recipes/assets/icon-512.png",
  "/recipes/assets/icon-maskable-512.png",
  "/recipes/assets/recipe.js",
  "/recipes/assets/search.js",
  "/recipes/assets/style.css",
  "/recipes/basics/harissa-paste/",
  "/recipes/basics/lemon-herb-tahini/",
  "/recipes/basics/quick-pickled-red-onions/",
  "/recipes/breakfast/yogurt-granola-and-strawberries/",
  "/recipes/drinks/ginger-mint-limeade/",
  "/recipes/",
  "/recipes/mains/cava-style-chicken/",
  "/recipes/mains/harissa-baked-feta-pasta/",
  "/recipes/mains/mediterranean-lunch-bowl/",
  "/recipes/manifest.webmanifest",
  "/recipes/search-index.json",
  "/recipes/sides/cucumber-tomato-salad/"
];

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(CACHE)
      .then((cache) => cache.addAll(PRECACHE))
      .then(() => self.skipWaiting())
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(
        keys.filter((key) => key !== CACHE).map((key) => caches.delete(key))
      ))
      .then(() => self.clients.claim())
  );
});

self.addEventListener('fetch', (event) => {
  const request = event.request;
  if (request.method !== 'GET') {
    return;
  }

  const url = new URL(request.url);
  if (url.origin !== self.location.origin || !url.pathname.startsWith(SCOPE)) {
    return;
  }

  event.respondWith(
    caches.match(request, { ignoreSearch: true }).then((hit) => {
      const fresh = fetch(request)
        .then((response) => {
          if (response && response.ok && response.type === 'basic') {
            const copy = response.clone();
            caches.open(CACHE).then((cache) => cache.put(request, copy));
          }
          return response;
        })
        .catch(() => {
          // Offline. A navigation with nothing cached still gets the home page,
          // which is enough to reach every recipe already in the cache.
          if (hit) {
            return hit;
          }
          return request.mode === 'navigate' ? caches.match(START_URL) : Response.error();
        });

      return hit || fresh;
    })
  );
});
